# pod 'cineio-peer-ios', :path => '/Users/thomas/work/cine-io/cineio-peer-ios'
pod 'cineio-peer-ios', '0.0.7'

# Add this to the bottom so it won't have issues with active architecture
post_install do |installer_representation|
    installer_representation.project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
            config.build_settings['VALID_ARCHS'] = ['armv7', 'armv7s']
        end
    end
end
